spring.application.name=pedidos360-backend
server.port=8080


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/5d020e86-60f8-47e9-9a84-7abf9906fdff/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/5d020e86-60f8-47e9-9a84-7abf9906fdff/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.audiences=1b54f9e6-dc5f-40a3-b612-f17203a45f15

# Configuración de conexión a la EC2 de RabbitMQ
spring.rabbitmq.host=3.95.247.162
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123